spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mpl

  profiles:
    default: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always

jwt:
  secret: ${JWT_SECRET}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  name: ${ADMIN_NAME}

tmdb:
  base-url: https://api.themoviedb.org/3
  image-base-url: https://image.tmdb.org/t/p/w500
  bearer-token: ${TMDB_BEARER_TOKEN}

sportsdb:
  base-url: https://www.thesportsdb.com/api/v1/json
  api-key: ${SPORTSDB_API_KEY}

mpl:
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.mpl/storage}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY:}
      secret-key: ${AWS_S3_SECRET_KEY:}
      region: ${AWS_S3_REGION:}
      bucket: ${AWS_S3_BUCKET:}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}

content:
  collection:
    scheduler:
      enabled: false
      cron: "0 0 3 * * *"
      zone: "Asia/Seoul"
