spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.mpdwgbbovescmmldaanm
    username: postgres
    password: KfMbG3SU5npmWtM2
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000
      leak-detection-threshold: 2000
      data-source-properties:
        # 1. 쿼리 준비 단계를 건너뛰도록 설정
        prepareThreshold: 0
        # 2. 드라이버 내부의 Prepared Statement 캐시 개수를 0으로 제한 (핵심)
        preparedStatementCacheQueries: 0
        # 3. 드라이버의 캐시 공간 크기를 0으로 제한 (핵심)
        preparedStatementCacheSizeMiB: 0

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always

  kafka:
    bootstrap-servers: localhost:29092

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  name: ${ADMIN_NAME}

tmdb:
  base-url: https://api.themoviedb.org/3
  image-base-url: https://image.tmdb.org/t/p/w500
  bearer-token: ${TMDB_BEARER_TOKEN}

sportsdb:
  base-url: https://www.thesportsdb.com/api/v1/json
  api-key: ${SPORTSDB_API_KEY}

content:
  collection:
    scheduler:
      enabled: false
      cron: "0 0 3 * * *"
      zone: "Asia/Seoul"
